# NUMPY 


Numpy is a low level library written in C for high level mathematical function numpy cleverly overcomes the problem of running slower algorithms on python by using multidimensional arrays and function that operates on arrays, 

In [7]:
import numpy as np

In [6]:
arr1=array([1,2,3,4])


In [11]:
#creating numpy arrray/n-d array
arr1=np.array([1,2,3,4])

arr1

array([1, 2, 3, 4])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
#2 d array
arr2=np.array([[1,2,3],[2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
arr3=np.zeros((2,3))
arr3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr4=np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr7=np.arange(2,10,3)  #(lower, upper, difference)
arr7

array([2, 5, 8])

In [30]:
arr8=np.linspace(10,20,10)   # (lower, upper, numper of points)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [31]:
arr9=arr7.copy()
arr9

array([2, 5, 8])

In [35]:
#shape
arr2.shape

(2, 3)

In [36]:
arr10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
arr10.shape

(2, 2, 2)

In [38]:
arr10.ndim   # number of dimension


3

In [39]:
arr1.size  #number of elements

4

In [40]:
arr10.size

8

In [42]:
arr10.itemsize   #bytes of datatype

4

In [43]:
arr10.dtype    #datatype


dtype('int32')

In [45]:
arr8.dtype

dtype('float64')

In [48]:
arr10.astype('float')
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## list vs arrays

1. faster
2. convenient
3. less memory

In [61]:
#prove that it take less memeory
lista=range(100)

arr11=np.arange(100)

import sys



In [62]:
print(sys.getsizeof(89)*len(lista))

2800


In [63]:
print(arr11.itemsize*arr11.size)

400


In [64]:
#prove for time
import time


In [65]:
x=range(100000)
y=range(100000)

In [68]:
start_time=time.time()

c=[x+y for x,y in zip(x,y)]

print(time.time()-start_time)

0.023239612579345703


In [69]:
arr12=np.arange(100000)
arr13=np.arange(100000)


In [71]:
start_time=time.time()
d=arr12+arr13

print(time.time()-start_time)



0.00099945068359375


In [77]:
arr14=np.arange(24).reshape(6,4)
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
arr14[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [85]:
arr14[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [90]:
arr14[4:,2:]

array([[18, 19],
       [22, 23]])

In [92]:
for i in np.nditer(arr14):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [93]:
arr15=np.array([1,2,3,45,6])
arr16=np.array([6,7,8,9,0])

In [94]:
arr15+arr16

array([ 7,  9, 11, 54,  6])

In [100]:
arr15*arr16 #vector multiplication

array([  6,  14,  24, 405,   0])

In [101]:
arr15-arr16

array([-5, -5, -5, 36,  6])

In [102]:
arr15*15    #scalar multiplication

array([ 15,  30,  45, 675,  90])

In [103]:
arr15>3


array([False, False, False,  True,  True])

In [106]:
#dot product
arr17=np.arange(10).reshape(2,5)
arr17

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
arr18=np.arange(10).reshape(5,2)
arr18

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
arr17.dot(arr18)

array([[ 60,  70],
       [160, 195]])

In [110]:
arr18.max()

9

In [114]:
arr14.min()

0

In [116]:
arr18.min(axis=0)   #minimum in every column

array([0, 1])

In [118]:
arr18.max(axis=1)       #max in every row

array([1, 3, 5, 7, 9])

In [119]:
arr18.sum(axis=1)

array([ 1,  5,  9, 13, 17])

In [121]:

arr18.std()


2.8722813232690143

In [122]:
np.sin(arr18)

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849]])

In [123]:
np.median(arr18)

4.5

## reshaping array

In [126]:
arr18.ndim


2

In [133]:
arr19=arr18.ravel()     # used to change the shape of array
arr19

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
arr18.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [138]:
#stacking : combining two array

arr20=np.arange(20).reshape(4,5)
arr20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
arr21=np.arange(20).reshape(4,5)
arr21

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
np.hstack((arr20,arr21))        #hosrizontal add

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [142]:
np.vstack((arr20,arr21))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [151]:
np.hsplit(arr20,5)


[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [152]:

np.vsplit(arr20,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [153]:
#fancy indexing
arr20[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])